export const NAVIGATE = 'NAVIGATE';
export const HANDLE_NAVIGATION_STATE = 'HANDLE_NAVIGATION_STATE';
export const RENDER_DESKTOP_NAVIGATION = 'RENDER_DESKTOP_NAVIGATION';
export const RENDER_MOBILE_NAVIGATION = 'RENDER_MOBILE_NAVIGATION';
